import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import axios from 'axios';
import { useState } from 'react';
import { Inter } from '@next/font/google'
import Header from '@/components/Header';
import Footer from '@/components/Footer';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState({})
  const [location, setLocation] = useState("");
  const [weather, setWeather] = useState();
  const [temperature, setTemperature] = useState();
  const [errorMessage, setErrorMessage] = useState('');

  let apiKey = process.env.NEXT_PUBLIC_WEATHER_API_KEY
  let lang = "en"
  let units = "metric"
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;

  const searchLocation = async (event) => {
    if (event.key === "Enter") {
      try {
        const response = await axios.get(url)
        const resdata = await response.data;
        setData(resdata)
        setTemperature(resdata.main)
        setWeather(resdata.weather)
        setErrorMessage("")
        console.log(resdata)

      }
      catch (error) {
        console.log(error);
        setErrorMessage("Please enter a valid location 🙉");
        setData({});
        setWeather();
        setTemperature();
      }
      setLocation('');
    }
  }

  return (
    <>
      <Head>
        <title>Simple Weather Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />

        <div className='h-screen mt-10 flex flex-col items-center'>
          <span className='text-red-500 font-bold text-lg'>{errorMessage}</span>
          <div className="flex flex-col gap-5 items-center">

          <input className="p-4" type="text" value={location} onChange={event => setLocation(event.target.value)} placeholder="enter location" onKeyDown={searchLocation} />
          <h1 className='mt-2'>{data.name && <><span className='font-bold text-5xl'>{data.name}</span></>}</h1>
          {
            weather && weather.map((w, i) => {
              return <div key={i}>
                <div className='capitalize'>{w.description}</div>
                {/* <div>{w.main}</div> */}
              </div>
            })
          }
          {temperature && <p>Temperature {temperature.temp}℃</p>}
          {temperature && <p>Feels like {temperature.feels_like}℃</p>}
          {data.wind && <p>Wind speed is {data.wind.speed}m/s</p>}
          </div>
        </div>

        <Footer />
      </main>
    </>
  )
}
