import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import axios from 'axios';
import { useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { motion } from 'framer-motion';
import WeatherCard from '@/components/WeatherCard';

export default function Home() {
  const [allData, setAllData] = useState([]);
  
  const [data, setData] = useState({})
  const [location, setLocation] = useState("");
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');

  let apiKey = process.env.NEXT_PUBLIC_WEATHER_API_KEY
  let lang = "en"
  let units = "metric"
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;

  const searchLocation = async (event) => {
    if (event.key === "Enter") {
      try {
        const response = await axios.get(url)
        const resdata = await response.data;
        setData(resdata)
        setWeather(resdata.weather)
        setErrorMessage("")
        console.log(resdata)

      }
      catch (error) {
        console.log(error);
        setErrorMessage("Please enter a valid location 🙉");
        setData({});
        setWeather();
      }
      setLocation('');
    }
  }

  return (
    <>
      <Head>
        <title>Simple Weather Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />

        <div className='h-screen mt-10 flex flex-col items-center' >
          {errorMessage && <motion.span initial={{ x: -50, opacity: 0 }} animate={{ x: 0, opacity: 1 }} className='text-red-500 font-bold text-lg'>{errorMessage}</motion.span>}
          <div className="flex flex-col gap-3 items-center">
            <input className="p-4 outline-none border-slate-500 border-2 rounded-lg" type="text" value={location} onChange={event => setLocation(event.target.value)} placeholder="enter location" onKeyDown={searchLocation} />
            {data.name && <WeatherCard data={data} />}
          </div>
        </div>

        <Footer />
      </main>
    </>
  )
}
