import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import axios from 'axios';
import { useState } from 'react';
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState({})
  const [location, setLocation] = useState("");
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');



  let apiKey = process.env.NEXT_PUBLIC_WEATHER_API_KEY
  let lang = "vi"
  let units = "metric"
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`

  const searchLocation = async (event) => {
    if (event.key === "Enter") {
      axios.get(url)
        .then((response) => {
          console.clear();
          setData(response.data)
          console.log(response.data)
          setErrorMessage("")
          setWeather(response.data.weather)
        })
        .catch((error) => {
          console.log(error)
          setErrorMessage("Please enter a valid location")
          setData({})
          setWeather()
        })
      setLocation('');
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {errorMessage}
        <input type="text" value={location} onChange={event => setLocation(event.target.value)} placeholder="enter location" onKeyDown={searchLocation} />
        {data.name}
        {
          weather && weather.map((w, i) => {
            return <div key={i}>
              <div>{w.description}</div>
              <div>{w.name}</div>
              <div>{w.main}</div>
            </div>
          })
        }
      </main>
    </>
  )
}
